name: ubenwa_thankgod
description: Ubenwa interview app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.3
  intl: ^0.18.0
  page_transition: ^2.1.0

dev_dependencies:  
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: ^2.1.7
  flutter_gen_runner: ^5.3.1


  
flutter_gen:
  output: lib/assets/
  line_length: 80

  integrations:
    flutter_svg: true
    json: true

  assets:
    enabled: true
    outputs:
      class_name: UbenwaAssets

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/svg/
    - assets/images/png/